frr defaults traditional
hostname Leaf1
service integrated-vtysh-config
!
interface eth1
 ip address 10.10.18.1/30
!
interface lo
 ip address 10.255.0.1/32
!
route-map PERMIT-ALL permit 10
!
router bgp 65101
 bgp router-id 10.255.0.1
 neighbor 10.10.18.2 remote-as 65000
 neighbor 10.255.0.2 remote-as 65102
 neighbor 10.255.0.2 update-source 10.255.0.1
 neighbor 10.255.0.2 ebgp-multihop 2
 !
 address-family ipv4 unicast
  network 10.255.0.1/32
  neighbor 10.10.18.2 route-map PERMIT-ALL in
  neighbor 10.10.18.2 route-map PERMIT-ALL out
 exit-address-family
!
 address-family l2vpn evpn
  neighbor 10.255.0.2 activate
  neighbor 10.255.0.2 route-map PERMIT-ALL in
  neighbor 10.255.0.2 route-map PERMIT-ALL out
  advertise-all-vni
!
  vni 10100
   route-target import 65000:10100
   route-target export 65000:10100
  exit-vni

 exit-address-family
!
line vty
!
