frr defaults traditional
hostname R3
service integrated-vtysh-config
!
interface eth1
 ip address 10.10.16.6/30
!
interface lo
 ip address 3.3.3.3/32
!
route-map PERMIT-ALL permit 10
!
router bgp 65003
 bgp router-id 3.3.3.3
 neighbor 10.10.16.5 remote-as 65002
 !
 address-family ipv4 unicast
  network 3.3.3.3/32
  neighbor 10.10.16.5 route-map PERMIT-ALL in
  neighbor 10.10.16.5 route-map PERMIT-ALL out
 exit-address-family
!
line vty
!
