frr defaults traditional
hostname Leaf2
service integrated-vtysh-config
!
interface eth1
 ip address 10.10.19.5/30
!
interface lo
 ip address 10.255.1.2/32
!
route-map PERMIT-ALL permit 10
!
vrf TENANT-A
 vni 10000
exit-vrf
!
router bgp 65102
 bgp router-id 10.255.1.2
 neighbor 10.10.19.6 remote-as 65000
 neighbor 10.255.1.1 remote-as 65101
 neighbor 10.255.1.1 update-source 10.255.1.2
 neighbor 10.255.1.1 ebgp-multihop 2
 !
 address-family ipv4 unicast
  network 10.255.1.2/32
  neighbor 10.10.19.6 route-map PERMIT-ALL in
  neighbor 10.10.19.6 route-map PERMIT-ALL out
 exit-address-family
!
 address-family l2vpn evpn
  neighbor 10.255.1.1 activate
  neighbor 10.255.1.1 route-map PERMIT-ALL in
  neighbor 10.255.1.1 route-map PERMIT-ALL out
  advertise-all-vni

 vni 10100
  route-target import 65000:10100
  route-target export 65000:10100
 exit-vni

 vni 10200
  route-target import 65000:10200
  route-target export 65000:10200
 exit-vni

 exit-address-family
!
router bgp 65102 vrf TENANT-A
 bgp router-id 10.255.1.2
 !
 address-family ipv4 unicast
  redistribute connected
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  route-target import 65000:10000
  route-target export 65000:10000
 exit-address-family
!
!
line vty
!

