frr defaults traditional
hostname Spine
service integrated-vtysh-config
!
interface eth1
 ip address 10.10.19.2/30
!
interface eth2
 ip address 10.10.19.6/30
!
interface lo
 ip address 10.255.1.254/32
!
route-map PERMIT-ALL permit 10
!
router bgp 65000
 bgp router-id 10.255.1.254
 neighbor 10.10.19.1 remote-as 65101
 neighbor 10.10.19.5 remote-as 65102
 !
 address-family ipv4 unicast
  network 10.255.1.254/32
  neighbor 10.10.19.1 route-map PERMIT-ALL in
  neighbor 10.10.19.1 route-map PERMIT-ALL out
  neighbor 10.10.19.5 route-map PERMIT-ALL in
  neighbor 10.10.19.5 route-map PERMIT-ALL out
 exit-address-family
!
line vty
!
