services:
  frr1:
    image: frrouting/frr:latest
    container_name: frr1
    hostname: frr1
    privileged: true
    tty: true
    volumes:
      - ./configs/frr1:/etc/frr
    networks:
      ospf_net:
        ipv4_address: 10.10.12.2

  frr2:
    image: frrouting/frr:latest
    container_name: frr2
    hostname: frr2
    privileged: true
    tty: true
    volumes:
      - ./configs/frr2:/etc/frr
    networks:
      ospf_net:
        ipv4_address: 10.10.12.3

networks:
  ospf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.12.0/24
