frr defaults traditional
hostname FRR1
service integrated-vtysh-config
!
interface lo
 ip address 1.1.1.1/32
!
route-map PERMIT-ALL permit 10
!
router bgp 65001
 bgp router-id 1.1.1.1
 neighbor 10.10.14.3 remote-as 65002
 !
 address-family ipv4 unicast
  network 1.1.1.1/32
  neighbor 10.10.14.3 route-map PERMIT-ALL in
  neighbor 10.10.14.3 route-map PERMIT-ALL out
 exit-address-family

!
line vty
!
