services:

  frr1:
    image: frrouting/frr:latest
    container_name: bgp-frr1
    privileged: true
    networks:
      bgp_net:
        ipv4_address: 10.10.14.2
    volumes:
      - ./configs/frr1:/etc/frr
    restart: unless-stopped

  frr2:
    image: frrouting/frr:latest
    container_name: bgp-frr2
    privileged: true
    networks:
      bgp_net:
        ipv4_address: 10.10.14.3
    volumes:
      - ./configs/frr2:/etc/frr
    restart: unless-stopped

networks:

  bgp_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.14.0/24
